version: 0.0.{build}

platform:
    - x86

skip_commits:
  message: /\[ci skip\]/

matrix:
    fast_finish: true

build_script:
    - SET PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
    - make all CC=gcc
    - for /f %%i in ('git describe --always') do set PRODUCT_VERSION=%%i
    - SET PRODUCT_NAME=esptool-%PRODUCT_VERSION%
    - SET PLATFORM_NAME=win32
    - SET PRODUCT_DIST_NAME=%PRODUCT_NAME%-%PLATFORM_NAME%
    - echo %PRODUCT_NAME%
    - echo %PRODUCT_DIST_NAME%
    - mkdir %PRODUCT_DIST_NAME%
    - cp esptool.exe %PRODUCT_DIST_NAME%\esptool.exe
    - SET PRODUCT_ZIP=%PRODUCT_DIST_NAME%.zip
    - 7z a %PRODUCT_ZIP% %PRODUCT_DIST_NAME%
    - appveyor PushArtifact %PRODUCT_ZIP%
    - SET PRODUCT_ZIP_SHA=%PRODUCT_ZIP%.sha
    - ps: Get-FileHash $env:PRODUCT_ZIP -Algorithm SHA1 | Out-File $env:PRODUCT_ZIP_SHA
    - type %PRODUCT_ZIP_SHA%
    - appveyor PushArtifact %PRODUCT_ZIP_SHA%

deploy:
    release: $(PRODUCT_VERSION)
    provider: GitHub
    auth_token:
        secure: 'PGg5fnoBpP1Omzr6f3KIYDiD8J30rretQjSl/MITRpzvSCmN88kM6VDMz1TBGZTA'
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
        appveyor_repo_tag: true
